// Quote reference and access-token patterns, shared so nrf-backend and
// nrf-frontend enforce the same shape instead of duplicating the regexes.
import joi from 'joi'

// Quote references are generated by the backend database as 'NRL-' plus six
// digits (backend changelog db.changelog-2.9.xml), and nrf-backend enforces
// the same pattern on its own reference params.
export const referencePattern = /NRL-\d{6}/

// Access-link tokens are URL-safe random strings issued by the backend.
export const tokenPattern = /[a-zA-Z0-9_-]+/

/**
 * Shared Joi fragment for a quote reference route param or query field.
 * @type {import('joi').StringSchema}
 */
export const referenceParam = joi
  .string()
  .pattern(new RegExp(`^${referencePattern.source}$`))
  .required()

/**
 * Shared Joi fragment for a quote access-link token.
 * @type {import('joi').StringSchema}
 */
export const tokenParam = joi
  .string()
  .pattern(new RegExp(`^${tokenPattern.source}$`))
  .required()
